server:
  port: 8081
logging:
  level:
    ROOT: INFO
    com.nl.cgi.bff: DEBUG
persistence:
  service:
    baseUrl: http://localhost:7001/
    userAuthenticationUrl: login-persistence-service/verify/userdetails
    saveUserDetails: login-persistence-service/save/userdetails
    countryDetails: login-persistence-service/country-details
    memorySizeInMb: 256
    readTimeOut: 120000
    writeTimeOut: 120000
    responseTimeOut: 120000
    connectionTimeOut: 1000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
